apiVersion: v1
kind: Service
metadata:
  name: {{ include "projeto-korp.fullname" . }}-app
  labels:
    {{- include "projeto-korp.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "projeto-korp.name" . }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ .Values.app.port }}
      targetPort: http
