apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "projeto-korp.fullname" . }}-app
  labels:
    {{- include "projeto-korp.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "projeto-korp.name" . }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "projeto-korp.labels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
          env:
            - name: HTTP_ADDRESS
              value: ":{{ .Values.app.port }}"
            {{- if .Values.app.otel.enabled }}
            - name: OTEL_TRACES_ENABLED
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.app.otel.endpoint | quote }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.app.otel.serviceName | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.resources.app | nindent 12 }}
