apiVersion: v1
kind: Service
metadata:
  name: {{ include "projeto-korp.fullname" . }}-nginx
  labels:
    {{- include "projeto-korp.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "projeto-korp.name" . }}
    app.kubernetes.io/component: nginx
  ports:
    - name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: http
