apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "projeto-korp.fullname" . }}-nginx
  labels:
    {{- include "projeto-korp.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "projeto-korp.name" . }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "projeto-korp.labels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "projeto-korp.fullname" . }}-nginx
