apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "projeto-korp.fullname" . }}-nginx
  labels:
    {{- include "projeto-korp.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
data:
  http-server-projeto-korp.conf: |
    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://{{ include "projeto-korp.fullname" . }}-app:{{ .Values.app.port }};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
