grafana:
  enabled: true
  adminPassword: admin
  service:
    type: ClusterIP
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
alertmanager:
  enabled: true
